services:
  postgres:
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: dam_user
      POSTGRES_PASSWORD: dam_dev_password
      POSTGRES_DB: dam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: